############################################################
# Launcher for Blast container for the eBioKit
# This is a template, the following values must be replaced:
#   - $${INSTANCE_NAME}, name for the instance
#   - $${INSTANCE_PORT_1}, port number 1 for the instance (nginx)
#   - $${INSTANCE_PORT_2}, port number 2 for the instance (Sequenceserver)
#   - $${ADMIN_USER}, name for admin user
#   - $${ADMIN_PASS}, password for admin user
############################################################

version: '2'
services:

    $${INSTANCE_NAME}-blast:
      image: fikipollo/blast
      container_name: $${INSTANCE_NAME}-blast
      depends_on:
        - $${INSTANCE_NAME}-data
      volumes_from:
        - $${INSTANCE_NAME}-data
      ports:
        - "$${INSTANCE_PORT_1}:80"
        - "$${INSTANCE_PORT_2}:4567"
      environment:
        - ADMIN_USER=$${ADMIN_USER}
        - ADMIN_PASS=$${ADMIN_PASS}

    $${INSTANCE_NAME}-data:
      image: busybox
      container_name: $${INSTANCE_NAME}-data
      volumes:
        - /data/$${INSTANCE_NAME}-data/db:/db
        - /data/$${INSTANCE_NAME}-data/tmp:/tmp
